USE DS_07;
-- CREATE TABLE VOTOS
CREATE TABLE VOTOS (
    ID TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
    VOTOS1 INT(10) UNSIGNED NOT NULL DEFAULT 0,
    VOTOS2 INT(10) UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);

-- INSER IN TABLE VOTOS VALUES
INSERT INTO VOTOS VALUES (1, 49, 12);

-- CREATE SP LIST VOTOS
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_LISTAR_VOTOS`()
BEGIN
    SELECT VOTOS1, VOTOS2 FROM VOTOS;
END;


-- CREATE SP UPDATE VOTOS
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ACTUALIZAR_VOTOS`(
    IN PARA_VOTOS1 INT(10) UNSIGNED,
    IN PARA_VOTOS2 INT(10) UNSIGNED
)
BEGIN
    SET @s = CONCAT("UPDATE VOTOS SET VOTOS1 =", PARA_VOTOS1, " , VOTOS2 =", PARA_VOTOS2);

    PREPARE stmt FROM @s;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END;