USE db_aa090b_ds7utp;

--CREATE TABLE ROLE
CREATE TABLE ROLE(
    ID_ROLE INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    ROL_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_ROLE)
);

-- INSER ROL IN TABLE|
INSERT INTO ROLE (ROL_NAME) VALUES
('ADMINISTRADOR'),
('PROFESOR'),
('ESTUDIANTE');


-- CREATE SP GET ROL
DROP PROCEDURE IF EXISTS SP_ROL_GET;
CREATE PROCEDURE SP_ROL_GET()
BEGIN
    SELECT ID_ROLE, ROL_NAME FROM ROLE;
END;

CALL SP_ROL_GET();

-- CREATE TABLE MENU
DROP TABLE IF EXISTS MENU;
CREATE TABLE MENU (
    ID_MENU INT NOT NULL,
    MEN_NAME VARCHAR(50) NOT NULL,
    IS_PARENT INT NOT NULL,
    ID_MENU_PARENT INT,
    MEN_URL VARCHAR(50) NULL
);
-- INSERT MENU
INSERT INTO MENU VALUES (1, 'USUARIO', 1, 0, NULL);
INSERT INTO MENU VALUES (101, 'REGISTRAR USUARIO', 0, 1, 'UserNew.php');
INSERT INTO MENU VALUES (102, 'LISTAR USUARIO', 0, 1, NULL);
INSERT INTO MENU VALUES (2, 'MATERIAS', 1, 0, NULL);
INSERT INTO MENU VALUES (201, 'REGISTRAR MATERIA', 0, 2);
INSERT INTO MENU VALUES (202, 'LISTAR MATERIA', 0, 2);
INSERT INTO MENU VALUES (3, 'NOTAS', 1, 0, NULL);
INSERT INTO MENU VALUES (301, 'REGISTRAR NOTAS', 0, 3);
INSERT INTO MENU VALUES (302, 'LISTAR NOTAS', 0, 3);


SELECT * FROM MENU WHERE ID_MENU <100;
-- CREATE TABLE PERMISSION
CREATE TABLE PERMISSION(
    ID_ROLE INT(10) UNSIGNED NOT NULL,
    ID_MENU INT(10) UNSIGNED NOT NULL
);




SELECT * FROM PERMISSION;
SELECT RO.ID_ROLE, RO.ROL_NAME
, ME.ID_MENU, ME.MEN_NAME, ME.ID_MENU_PARENT, IFNULL(ME.MEN_URL, "#") AS MEN_URL  FROM ROLE RO 
INNER JOIN PERMISSION PE ON RO.ID_ROLE = PE.ID_ROLE
INNER JOIN MENU ME ON ME.ID_MENU = PE.ID_MENU
 
;

CREATE TABLE `parameter` (
  `ID_PARAMETER` int unsigned NOT NULL AUTO_INCREMENT,
  `PAR_NAME` varchar(50) NOT NULL,
  `PAR_VALUE` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_PARAMETER`)
)

SELECT  * FROM PARAMETER;

CREATE PROCEDURE SP_GENDER_GET()
BEGIN
    SELECT ID_PARAMETER, PAR_NAME, PAR_VALUE FROM PARAMETER WHERE PAR_NAME = 'GENERO';
END;

CALL SP_GENDER_GET();