USE db_aa090b_ds7utp;

--CREATE TABLE ROLE
CREATE TABLE ROLE(
    ID_ROLE INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    ROL_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_ROLE)
);

-- INSER ROL IN TABLE|
INSERT INTO ROLE (ROL_NAME) VALUES
('ADMINISTRADOR'),
('ESTUDIANTE'),
('PROFESOR');

-- CREATE SP GET ROL
DROP PROCEDURE IF EXISTS SP_ROL_GET;
CREATE PROCEDURE SP_ROL_GET()
BEGIN
    SELECT ID_ROLE, ROL_NAME FROM ROLE;
END;

CALL SP_ROL_GET();

-- CREATE TABLE MENU
CREATE TABLE MENU(
    ID_MENU INT(10) UNSIGNED NOT NULL,
    MEN_NAME VARCHAR(50) NOT NULL,
    IS_PARENT INT NOT NULL
    ID_MENU_PARENT INT(10) UNSIGNED NOT NULL
);

-- INSERT MENU
INSERT INTO MENU VALUES (1, 'USUARIO', 1, 0);
INSERT INTO MENU VALUES (101, 'REGISTRAR USUARIO', 0, 1);
INSERT INTO MENU VALUES (102, 'LISTAR USUARIO', 0, 1);
INSERT INTO MENU VALUES (2, 'MATERIAS', 1, 0);
INSERT INTO MENU VALUES (201, 'REGISTRAR MATERIA', 0, 2);
INSERT INTO MENU VALUES (202, 'LISTAR MATERIA', 0, 2);
INSERT INTO MENU VALUES (3, 'NOTAS', 1, 0);
INSERT INTO MENU VALUES (301, 'REGISTRAR NOTAS', 0, 3);
INSERT INTO MENU VALUES (302, 'LISTAR NOTAS', 0, 3);



-- CREATE TABLE PERMISSION
CREATE TABLE PERMISSION(
    ID_ROLE INT(10) UNSIGNED NOT NULL,
    ID_MENU INT(10) UNSIGNED NOT NULL
);