-- create table class
CREATE TABLE IF NOT EXISTS CLASS(
    ID_CLASS SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
    CLA_NAME VARCHAR(20) NOT NULL,
    CLA_COD VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_CLASS)
)


-- CREA SP NEW CLASS
CREATE PROCEDURE SP_CLASS_NEW(
    IN VAR_CLA_NAME VARCHAR(50),
    IN VAR_CLA_COD VARCHAR(50)
)
BEGIN
    INSERT INTO CLASS(CLA_NAME, CLA_COD)
    SELECT VAR_CLA_NAME, VAR_CLA_COD
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM CLASS WHERE CLA_COD = VAR_CLA_COD);
    SELECT 1 AS RESPONSE;

END

-- CREA SP GET CLASS
DROP PROCEDURE IF EXISTS SP_CLASS_NEW;

CREATE PROCEDURE SP_CLASS_GET()
BEGIN
SELECT ID_CLASS ,CLA_NAME ,CLA_COD  FROM CLASS;
END;

CALL SP_CLASS_GET();